### ISSUE TITLE
Investigate BAM files from the GDC

### ISSUE THREAD

**Issue by agduncan94** [agduncan94/gdc-viewer#79]
Investigate whether BAM files downloaded from the GDC portal work with the [alignment track type](https://jbrowse.org/docs/alignments.html#:~:text=Introduced%20in%20JBrowse%201.7.,click%20menus%20and%20strand%20arrowheads.).

There are two parts to this.
1) Download a BAM file and generate the index file locally. Using these two files, create an alignment track. Does this work?
2) Find a BAM file with an existing index. Set the URLtemplate path of an alignment track (and index path) to these locations (requires using the [authentication token](https://docs.gdc.cancer.gov/API/Users_Guide/Getting_Started/#authentication))

Use `samtools index` to generate the index file. See [here](http://quinlanlab.org/tutorials/samtools/samtools.html#:~:text=of%20the%20alignments%3F-,samtools%20%E2%80%9Cindex%E2%80%9D,region%20to%20which%20you%20navigate.).

Post your results to the investigation as a comment here.

**Comment by agduncan94** [comment]
The GDC API has the concept of related files, which might be relevant for finding associated index files.
https://docs.gdc.cancer.gov/API/Users_Guide/Downloading_Files/#related-files

**Comment by GFJHogue** [comment]
> 1. Download a BAM file and generate the index file locally. Using these two files, create an alignment track. Does this work?

Confirmed that this works as stated. Downloaded a BAM, unzipped with `tar -xf`, generated the index with `samtools index`, and created an alignment track.

**Comment by GFJHogue** [comment]
Demonstrated adding a BAM track via URL with authentication token in #98
