### ISSUE TITLE
Investigate the GDC BAM Slicing API

### ISSUE THREAD

**Issue by agduncan94** [agduncan94/gdc-viewer#82]
The GDC API supports BAM slicing (https://docs.gdc.cancer.gov/API/Users_Guide/BAM_Slicing/)

Unfortunately, it doesn't provide an index file, so we would need to have the user generate this.

Try using the BAM slicing API to slice a BAM file. Then use `samtools index` to create an index and try using the alignment track to display.

**Comment by GFJHogue** [comment]
We found that the GDC API _does_ provide index files for BAMs. Therefore this investigation is not needed.
