### ISSUE TITLE
Open BAM and BAI files in the Add track menu

### ISSUE THREAD

**Issue by agduncan94** [agduncan94/gdc-viewer#89]
It seems like the convention for naming some bam and bai files from the gdc are alignment.bam and alignment.bai. There is some JBrowse code that assumes the naming convention is something like alignment.bam and alignment.bam.bai. The bai file has the same name as the bam, but with .bai appended to it.

When you try to add the track using the Track -> Add track from file or URL, it assumes that the bam and bai files follow the naming convention mentioned above. This should be fixed to allow users to add these bam and bai files where the name, ignoring the .bam and .bam.bai is the same.

This is related to https://github.com/GMOD/jbrowse/issues/1538.

**Comment by agduncan94** [comment]
Notes
* code goes to BAMDriver.js
* connected to multiindexedfiledriver

**Comment by GFJHogue** [comment]
This also appears to affect VCFs with their `.tbi` index files.

Seems to me that this won't change anytime soon.
This only really affects users uploading tracks manually, so it's probably not a big deal for them to rename index files...

As for our own "Add Files from GDC" interfaces, this doesn't affect us and the `BAM` store class doesn't care.
It's easy enough to hypothetically support uploading files on a `gdc-viewer`-specific interface.
Closing (and replacing with a new issue).
